apiVersion: v1
data:
  insecure: dHJ1ZQ==
  password: eW91cmVhbGx5dGhpbmt0aGlzaXNhdmFsaWRzZWNyZXQ/
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRsYWIuZXhhbXBsZS5jb20va3ViZXJuZXRlcy9naXRvcHMuZ2l0
  username: dXNlcg==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repocreds
  namespace: argocd
type: Opaque
